[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Redirects for clean URLs
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
