import type { VendorTool } from '@/types/core';

export const vendorTools: VendorTool[] = [
  {
    id: 'openai-consumer',
    name: 'ChatGPT (Free/Plus)',
    vendor: 'OpenAI',
    surface: 'Consumer',
    trainsOnDataByDefault: true,
    privacyPolicyUrl: 'https://openai.com/policies/privacy-policy',
    pricingUrl: 'https://openai.com/pricing',
    suitableForTiers: ['T0'],
  },
  {
    id: 'openai-enterprise',
    name: 'ChatGPT Enterprise',
    vendor: 'OpenAI',
    surface: 'Enterprise',
    trainsOnDataByDefault: false,
    privacyPolicyUrl: 'https://openai.com/enterprise-privacy',
    pricingUrl: 'https://openai.com/chatgpt/enterprise',
    suitableForTiers: ['T1', 'T2', 'T3'],
  },
  {
    id: 'anthropic-consumer',
    name: 'Claude (Free)',
    vendor: 'Anthropic',
    surface: 'Consumer',
    trainsOnDataByDefault: false,
    privacyPolicyUrl: 'https://www.anthropic.com/legal/privacy',
    pricingUrl: 'https://www.anthropic.com/pricing',
    suitableForTiers: ['T0'],
  },
  {
    id: 'anthropic-enterprise',
    name: 'Claude for Work',
    vendor: 'Anthropic',
    surface: 'Enterprise',
    trainsOnDataByDefault: false,
    privacyPolicyUrl: 'https://www.anthropic.com/legal/privacy',
    pricingUrl: 'https://www.anthropic.com/claude/pricing',
    suitableForTiers: ['T1', 'T2', 'T3'],
  },
  {
    id: 'google-gemini',
    name: 'Google Gemini',
    vendor: 'Google',
    surface: 'Consumer',
    trainsOnDataByDefault: true,
    privacyPolicyUrl: 'https://policies.google.com/privacy',
    pricingUrl: 'https://ai.google.dev/pricing',
    suitableForTiers: ['T0'],
  },
  {
    id: 'microsoft-copilot',
    name: 'Microsoft 365 Copilot',
    vendor: 'Microsoft',
    surface: 'Enterprise',
    trainsOnDataByDefault: false,
    privacyPolicyUrl: 'https://privacy.microsoft.com/en-us/privacystatement',
    pricingUrl: 'https://www.microsoft.com/en-us/microsoft-365/business/copilot-for-microsoft-365',
    suitableForTiers: ['T1', 'T2', 'T3'],
  },
];
